const events = new Map();
events.set('auctionBid', 'NounsDAO.AuctionBid');
events.set('auctionCreated', 'NounsDAO.AuctionCreated');
events.set('delegateChanged', 'NounsDAO.DelegateChanged');
events.set('delegateChangedNoZero', 'NounsDAO.DelegateChangedNoZero');
events.set('newPost', 'NounsNymz.NewPost');
events.set('newProposalPoll', 'Nerman.NewProposalPoll');
events.set('nounCreated', 'NounsDAO.NounCreated');
events.set('propCreated', 'NounsDAO.PropCreated');
events.set('propStatusChange', 'NounsDAO.PropStatusChange');
events.set('propVoteCast', 'NounsDAO.PropVoteCast');
events.set('threadVote', 'Nerman.ThreadVote');
events.set('threadStatusChange', 'Nerman.ThreadStatusChange');
events.set('transferNoun', 'NounsDAO.TransferNoun');
module.exports = events;
